require 'dynamoid'
require 'activity_notification/apis/notification_api'

module ActivityNotification
  module ORM
    module Dynamoid
      # Notification model implementation generated by ActivityNotification.
      class Notification
        include ::Dynamoid::Document
        include ActiveModel::AttributeAssignment
        include GlobalID::Identification
        include DynamoidExtension
        include Common
        include Renderable
        include Association
        include NotificationApi

        table name: ActivityNotification.config.notification_table_name, key: :id

        # @@date_time_dumper = ::Dynamoid::Dumping::DateTimeDumper.new({})

        # Belongs to target instance of this notification as polymorphic association using composite key.
        # @scope instance
        # @return [Object] Target instance of this notification
        belongs_to_composite_xdb_record :target

        # Belongs to notifiable instance of this notification as polymorphic association using composite key.
        # @scope instance
        # @return [Object] Notifiable instance of this notification
        belongs_to_composite_xdb_record :notifiable

        # Belongs to group instance of this notification as polymorphic association using composite key.
        # @scope instance
        # @return [Object] Group instance of this notification
        belongs_to_composite_xdb_record :group

        # Belongs to :otifier instance of this notification.
        # @scope instance
        # @return [Object] Notifier instance of this notification
        belongs_to_composite_xdb_record :notifier

        field :key,            :string
        field :parameters,     :raw,      default: {}
        field :opened_at,      :datetime, store_as_string: true
        field :group_owner_id, :string

        # Belongs to group owner notification instance of this notification.
        # Only group member instance has :group_owner value.
        # Group owner instance has nil as :group_owner association.
        # @scope instance
        # @return [Notification] Group owner notification instance of this notification
        belongs_to :group_owner, { class_name: "ActivityNotification::Notification", foreign_key: :group_owner_id }.merge(Rails::VERSION::MAJOR >= 5 ? { optional: true } : {})

        # Has many group member notification instances of this notification.
        # Only group owner instance has :group_members value.
        # Group member instance has nil as :group_members association.
        # @scope instance
        # @return [Dynamoid::Criteria::Chain] Database query of the group member notification instances of this notification
        # has_many   :group_members, class_name: "ActivityNotification::Notification", foreign_key: :group_owner_id
        def group_members
          Notification.where(group_owner_id: id)
        end

        global_secondary_index hash_key: :target_key,     range_key: :created_at, projected_attributes: :all
        global_secondary_index hash_key: :notifiable_key, range_key: :created_at, projected_attributes: :all
        global_secondary_index hash_key: :notifier_key,   range_key: :created_at, projected_attributes: :all
        global_secondary_index hash_key: :group_owner_id, range_key: :created_at, projected_attributes: :all

        validates  :target,        presence: true
        validates  :notifiable,    presence: true
        validates  :key,           presence: true

        %i[ all_index! unopened_index opened_index
            filtered_by_association filtered_by_target filtered_by_instance filtered_by_group
            filtered_by_target_type filtered_by_type filtered_by_key filtered_by_options
            latest_order earliest_order
            group_owners_only group_members_only unopened_only opened_only! opened_only
            unopened_index_group_members_only opened_index_group_members_only
            within_expiration_only(expiry_delay
            group_members_of_owner_ids_only
            reload
            latest earliest
            uniq_keys
          ].each do |method|
          # Return a criteria chain in response to a method that will begin or end a chain.
          # For more information, see Dynamoid::Criteria::Chain.
          singleton_class.send(:define_method, method) do |*args, &block|
            # Use scan_index_forward with true as default value to convert Dynamoid::Document into Dynamoid::Criteria::Chain
            # https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/document.rb
            # https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/components.rb
            # https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/criteria.rb
            # https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/criteria/chain.rb
            scan_index_forward(true).send(method, *args, &block)
          end
        end

        %i[ with_target with_notifiable with_group with_group_owner with_group_members with_notifier ].each do |method|
          singleton_class.send(:define_method, method) do |*args, &block|
            self
          end
        end

        # Returns if the notification is group owner.
        # Calls NotificationApi#group_owner? as super method.
        # @return [Boolean] If the notification is group owner
        def group_owner?
          super
        end

        # Raise DeleteRestrictionError for notifications.
        # This method raises RuntimeError instead of DeleteRestrictionError not to have ActiveRecord dependency.
        # @param [String] error_text Error text for raised exception
        # @raise RuntimeError
        # @return [void]
        def self.raise_delete_restriction_error(error_text)
          raise error_text
        end

        # Returns valid group owner within the expiration period
        # 
        # @param [Object]                  target             Target to send notifications
        # @param [Object]                  notifiable         Notifiable instance
        # @param [String]                  key                Key of the notification
        # @param [Object]                  group              Group unit of the notifications
        # @param [ActiveSupport::Duration] group_expiry_delay Expiry period of a notification group
        # @return [Notificaion] Valid group owner within the expiration period
        # def self.valid_group_owner(target, notifiable, key, group, group_expiry_delay)
            # return nil if group.blank?
          # # Bundle notification group by target, notifiable_type, group and key
          # # Different notifiable.id can be made in a same group
          # query_key = "#{notifiable.to_class_name}#{ActivityNotification.config.composite_key_delimiter}#{key}#{ActivityNotification.config.composite_key_delimiter}#{group.class.name}#{ActivityNotification.config.composite_key_delimiter}#{group.id}"
          # group_owner_notifications = filtered_by_target(target).where('unopened_group_owner_key.begins_with': query_key)
          # group_owner_notifications = group_expiry_delay.present? ?
            # group_owner_notifications.where('unopened_group_owner_key.gt': "#{query_key}#{ActivityNotification.config.composite_key_delimiter}#{@@date_time_dumper.process(expiry_delay.ago)}") :
            # group_owner_notifications
          # group_owner_notifications.earliest
        # end

        # Returns prepared notification object to store
        # @return [Object] prepared notification object to store
        # def prepare_to_store
          # if group_owner? && unopened?
            # self.unopened_group_owner_key = "#{notifiable_key.split(ActivityNotification.config.composite_key_delimiter).first}#{ActivityNotification.config.composite_key_delimiter}#{key}#{ActivityNotification.config.composite_key_delimiter}#{group_key}#{ActivityNotification.config.composite_key_delimiter}#{@@date_time_dumper.process(created_at)}"
          # end
          # self
        # end

        # Opens the notification.
        #
        # @param [Hash] options Options for opening notifications
        # @option options [DateTime] :opened_at   (Time.current) Time to set to opened_at of the notification record
        # @option options [Boolean] :with_members (true)         If it opens notifications including group members
        # @return [Integer] Number of opened notification records
        # def open!(options = {})
          # opened? and return 0
          # opened_at    = options[:opened_at] || Time.current
          # with_members = options.has_key?(:with_members) ? options[:with_members] : true
          # unopened_member_count = with_members ? group_members.unopened_only.count : 0
          # group_members.update_all(opened_at: opened_at) if with_members
          # update_attributes(opened_at: opened_at)
          # unopened_member_count + 1
        # end

        protected

          # Returns count of group members of the unopened notification.
          # This method is designed to cache group by query result to avoid N+1 call.
          # @api protected
          # @todo Avoid N+1 call
          #
          # @return [Integer] Count of group members of the unopened notification
          def unopened_group_member_count
            group_members.unopened_only.count
          end

          # Returns count of group members of the opened notification.
          # This method is designed to cache group by query result to avoid N+1 call.
          # @api protected
          # @todo Avoid N+1 call
          #
          # @param [Integer] limit Limit to query for opened notifications
          # @return [Integer] Count of group members of the opened notification
          def opened_group_member_count(limit = ActivityNotification.config.opened_index_limit)
            limit == 0 and return 0
            group_members.opened_only(limit).to_a.length
          end

          # Returns count of group member notifiers of the unopened notification not including group owner notifier.
          # This method is designed to cache group by query result to avoid N+1 call.
          # @api protected
          # @todo Avoid N+1 call
          #
          # @return [Integer] Count of group member notifiers of the unopened notification
          def unopened_group_member_notifier_count
            group_members.unopened_only
                         .filtered_by_association_type("notifier", notifier)
                         .where("notifier_key.ne": notifier_key)
                         .all.to_a
                         .collect {|n| n.notifier_key }.uniq
                         .length
          end

          # Returns count of group member notifiers of the opened notification not including group owner notifier.
          # This method is designed to cache group by query result to avoid N+1 call.
          # @api protected
          # @todo Avoid N+1 call
          #
          # @param [Integer] limit Limit to query for opened notifications
          # @return [Integer] Count of group member notifiers of the opened notification
          #TODO
          def opened_group_member_notifier_count(limit = ActivityNotification.config.opened_index_limit)
            limit == 0 and return 0
            group_members.opened_only(limit)
                         .filtered_by_association_type("notifier", notifier)
                         .where("notifier_key.ne": notifier_key)
                         .all.to_a
                         .collect {|n| n.notifier_key }.uniq
                         .length
          end

      end
    end
  end
end
